plugins {
    id 'com.android.application'
}

android {
    namespace 'com.valterc.ki2.sampleprovider'
    compileSdk 34

    defaultConfig {
        applicationId 'com.valterc.ki2.sampleprovider'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
